.nh
.TH "GUMROAD" "1" "Sep 2026" "Gumroad" "Gumroad CLI"

.SH NAME
gumroad-products-covers - Manage product cover images


.SH SYNOPSIS
\fBgumroad products covers [flags]\fP


.SH DESCRIPTION
Manage product cover images


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for covers


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug logging to stderr

.PP
\fB--dry-run\fP[=false]
	Preview mutating requests without executing them

.PP
\fB--jq\fP=""
	Filter JSON output with a jq expression

.PP
\fB--json\fP[=false]
	Output as JSON

.PP
\fB--no-color\fP[=false]
	Disable color output

.PP
\fB--no-image\fP[=false]
	Disable image rendering

.PP
\fB--no-input\fP[=false]
	Disable interactive prompts

.PP
\fB--non-interactive\fP[=false]
	Run in explicit CI/agent mode

.PP
\fB--page-delay\fP=0s
	Wait between paginated --all requests (e.g. 200ms, 1s)

.PP
\fB--plain\fP[=false]
	Output as plain tab-separated text

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--yes\fP[=false]
	Skip confirmation prompts


.SH EXAMPLE
.EX
  gumroad products covers add <product_id> --image ./cover.jpg
  gumroad products covers add <product_id> --url https://www.youtube.com/watch?v=qKebcV1jv3A
  gumroad products covers remove <product_id> <cover_id>
  gumroad products covers reorder <product_id> <cover_id> <cover_id>
.EE


.SH SEE ALSO
\fBgumroad-products(1)\fP, \fBgumroad-products-covers-add(1)\fP, \fBgumroad-products-covers-remove(1)\fP, \fBgumroad-products-covers-reorder(1)\fP
