.nh
.TH "GUMROAD" "1" "Sep 2026" "Gumroad" "Gumroad CLI"

.SH NAME
gumroad-admin-payouts-scheduled - Inspect and act on ScheduledPayout records


.SH SYNOPSIS
\fBgumroad admin payouts scheduled [flags]\fP


.SH DESCRIPTION
Inspect and act on ScheduledPayout records


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for scheduled


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug logging to stderr

.PP
\fB--dry-run\fP[=false]
	Preview mutating requests without executing them

.PP
\fB--jq\fP=""
	Filter JSON output with a jq expression

.PP
\fB--json\fP[=false]
	Output as JSON

.PP
\fB--no-color\fP[=false]
	Disable color output

.PP
\fB--no-image\fP[=false]
	Disable image rendering

.PP
\fB--no-input\fP[=false]
	Disable interactive prompts

.PP
\fB--non-interactive\fP[=false]
	Run in explicit CI/agent mode

.PP
\fB--page-delay\fP=0s
	Wait between paginated --all requests (e.g. 200ms, 1s)

.PP
\fB--plain\fP[=false]
	Output as plain tab-separated text

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--yes\fP[=false]
	Skip confirmation prompts


.SH EXAMPLE
.EX
  gumroad admin payouts scheduled list
  gumroad admin payouts scheduled list --status flagged
  gumroad admin payouts scheduled create --user-id 2245593582708 --processor stripe --yes
  gumroad admin payouts scheduled execute pay_abc123 --yes
  gumroad admin payouts scheduled cancel pay_abc123
.EE


.SH SEE ALSO
\fBgumroad-admin-payouts(1)\fP, \fBgumroad-admin-payouts-scheduled-cancel(1)\fP, \fBgumroad-admin-payouts-scheduled-create(1)\fP, \fBgumroad-admin-payouts-scheduled-execute(1)\fP, \fBgumroad-admin-payouts-scheduled-list(1)\fP
