.nh
.TH "GUMROAD" "1" "Sep 2026" "Gumroad" "Gumroad CLI"

.SH NAME
gumroad-emails-create - Create an audience email


.SH SYNOPSIS
\fBgumroad emails create [flags]\fP


.SH DESCRIPTION
Create an audience email from an HTML body file.

.PP
Emails are created as drafts. Pass --send only when you intend to publish and
send the email to its audience immediately.


.SH OPTIONS
\fB--audience\fP="all"
	Audience: all, customers, followers, product

.PP
\fB--body\fP=""
	Path to an HTML body file, or - for stdin (required)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--product\fP=""
	Product ID when --audience product

.PP
\fB--send\fP[=false]
	Publish and send immediately

.PP
\fB--subject\fP=""
	Email subject (required)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug logging to stderr

.PP
\fB--dry-run\fP[=false]
	Preview mutating requests without executing them

.PP
\fB--jq\fP=""
	Filter JSON output with a jq expression

.PP
\fB--json\fP[=false]
	Output as JSON

.PP
\fB--no-color\fP[=false]
	Disable color output

.PP
\fB--no-image\fP[=false]
	Disable image rendering

.PP
\fB--no-input\fP[=false]
	Disable interactive prompts

.PP
\fB--non-interactive\fP[=false]
	Run in explicit CI/agent mode

.PP
\fB--page-delay\fP=0s
	Wait between paginated --all requests (e.g. 200ms, 1s)

.PP
\fB--plain\fP[=false]
	Output as plain tab-separated text

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--yes\fP[=false]
	Skip confirmation prompts


.SH EXAMPLE
.EX
  gumroad emails create --subject "New release" --body ./email.html
  gumroad emails create --subject "Product update" --body ./email.html --audience product --product <id>
  gumroad emails create --subject "Launch now" --body ./email.html --send --yes
  build-email | gumroad emails create --subject "From stdin" --body -
  gumroad emails create --subject "Check params" --body ./email.html --dry-run
.EE


.SH SEE ALSO
\fBgumroad-emails(1)\fP
