.nh
.TH "GUMROAD" "1" "Sep 2026" "Gumroad" "Gumroad CLI"

.SH NAME
gumroad-admin-products-view - View an admin product record


.SH SYNOPSIS
\fBgumroad admin products view  [flags]\fP


.SH DESCRIPTION
View an admin product record


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for view

.PP
\fB--with-fraud-context\fP[=false]
	Request expensive fraud context such as recent chargeback rate


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--debug\fP[=false]
	Enable debug logging to stderr

.PP
\fB--dry-run\fP[=false]
	Preview mutating requests without executing them

.PP
\fB--jq\fP=""
	Filter JSON output with a jq expression

.PP
\fB--json\fP[=false]
	Output as JSON

.PP
\fB--no-color\fP[=false]
	Disable color output

.PP
\fB--no-image\fP[=false]
	Disable image rendering

.PP
\fB--no-input\fP[=false]
	Disable interactive prompts

.PP
\fB--non-interactive\fP[=false]
	Run in explicit CI/agent mode

.PP
\fB--page-delay\fP=0s
	Wait between paginated --all requests (e.g. 200ms, 1s)

.PP
\fB--plain\fP[=false]
	Output as plain tab-separated text

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-essential output

.PP
\fB--yes\fP[=false]
	Skip confirmation prompts


.SH EXAMPLE
.EX
  gumroad admin products view abc123
  gumroad admin products view abc123 --with-fraud-context
  gumroad admin products view abc123 --json
.EE


.SH SEE ALSO
\fBgumroad-admin-products(1)\fP
